const JWT_ENGINEER_PASSWORD = process.env.JWT_ENGINEER_PASSWORD;
const JWT_MANAGER_PASSWORD = process.env.JWT_MANAGER_PASSWORD;


module.exports = {
    JWT_ENGINEER_PASSWORD, 
    JWT_MANAGER_PASSWORD
}